<a href="https://colab.research.google.com/github/Zaratrusztra/Zaratrusztra/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pierwsze działania na tensorflow


In [1]:
import tensorflow as tf

In [2]:
#łądowanie danych badawczych mnist
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 0s 0us/step


In [3]:
# budowa modelu
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.470931  ,  0.44867882, -0.09776983,  0.16334832, -0.46656585,
        -1.1841568 , -0.58219445,  0.07955148,  0.2620371 , -0.32719514]],
      dtype=float32)

In [6]:
""" Funkcja tf.nn.softmax konwertuje te logi na „prawdopodobieństwa” dla każdej klasy:"""

tf.nn.softmax(predictions).numpy()


array([[0.07039602, 0.17657515, 0.10223744, 0.13274315, 0.07070398,
        0.03449833, 0.06298353, 0.12207299, 0.14651163, 0.08127777]],
      dtype=float32)

In [8]:
#losses.SparseCategoricalCrossentropy przyjmują wektor logitów oraz indeks True i zwracają stratę skalarną dla każdego przykładu.

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [9]:
loss_fn(y_train[:1], predictions).numpy()


3.3668444

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [12]:
#Metoda Model.fit dostosowuje parametry modelu, aby zminimalizować straty:

model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2935 - accuracy: 0.9145
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1412 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1071 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0888 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0756 - accuracy: 0.9769


In [13]:
 #Metoda Model.evaluate sprawdza wydajność modeli, zwykle na „ zestawie walidacyjnym ” lub „ zestawie testowym ”.

model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0743 - accuracy: 0.9780


[0.07430590689182281, 0.9779999852180481]

In [14]:
#Jeśli chcesz, aby Twój model zwrócił prawdopodobieństwo, możesz zawinąć wytrenowany model i dołączyć do niego softmax:

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.00249929e-06, 6.62040875e-08, 3.44302225e-06, 6.75813295e-04,
        3.42177758e-10, 1.14790873e-06, 6.94867937e-13, 9.99307632e-01,
        1.70236297e-06, 9.12531505e-06],
       [5.08248320e-07, 7.06785286e-05, 9.99923229e-01, 3.43908346e-06,
        1.10908055e-13, 9.13730389e-08, 8.42491090e-07, 2.54338078e-11,
        1.18916842e-06, 4.75134376e-11],
       [1.13021429e-06, 9.89183784e-01, 8.85974558e-04, 4.26106089e-05,
        4.93510270e-05, 8.58535714e-06, 3.49866605e-04, 8.01828224e-03,
        1.45968189e-03, 5.98424435e-07],
       [9.99960423e-01, 5.01557729e-09, 3.52554634e-05, 5.65165514e-09,
        9.64191003e-08, 2.19483269e-07, 4.62177411e-07, 4.36926911e-07,
        5.73762093e-10, 3.09488428e-06],
       [3.80637721e-05, 1.32364413e-08, 1.62434717e-05, 4.75419768e-07,
        9.79033291e-01, 2.15843670e-06, 6.86593785e-06, 2.52763275e-04,
        1.04536753e-06, 2.06490625e-02]], dtype=float32)>

### Klasyfikacja podstawowa: Klasyfikuj obrazy odzieży


In [15]:
# TensorFlow and tf.keras
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)


2.3.0
